<?php

return [
    'types' => [
        'Automovil',
        'Vagoneta',
        'Camioneta',
        'Minibus',
        'Jeep',
        'Colectivo',
        'Camión',
        'Motocicleta, Quadratrack',
        'Bus',
        'Tractocamión',
        'Micro Bus (9 a 25)',
        'Furgoneta',
    ],

    'makes' => [
        'ACURA'         => [ 'models' => [ 'MDX', ] ],
        'ADIGE'         => [ 'models' => [ 'ADIGE', ] ],
        'AGRALE'        => [ 'models' => [ '1600 D-RS', '1800 D', '4001 CC.', ] ],
        'ALFA ROMEO'    => [ 'models' => [ 'ALFETTA', 'SPIDER VELOCE 2000', ] ],
        'ALGA'          => [ 'models' => [ 'SEMIRREMOLQUE LOWBOYTLS50', ] ],
        'AMERICA'       => [ 'models' => [ 'GENERAL CAMION', ] ],
        'APRILIA'       => [ 'models' => [ 'CRIMBER MOTO. 270 CC.', 'GUZZI MOTO. 250 CC.', ] ],
        'ASIA'          => [ 'models' => [ 'COSMOS', 'KOMBI MICROBUS', 'TOPIC', 'TOWNER', ] ],
        'ASIMEC'        => [ 'models' => [ 'SEMIREMOLQUE', ] ],
        'ASIMEX'        => [ 'models' => [ 'REMOLQUE', ] ],
        'ASTRA'         => [ 'models' => [ 'ASTRA', ] ],
        'AUAPA'         => [ 'models' => [ 'OB110-8B', ] ],
        'AUDI'          => [
            'models' => [
                'A1',
                'A1',
                'A3',
                'A4',
                'A4 BERLINA',
                'A5 CABRIOLET',
                'A6',
                'CD100',
                'K7',
                'Q3',
                'Q5',
                'Q7',
                'S4',
                'S5',
                'TT',
            ]
        ],
        'AUSTIN'        => [ 'models' => [ 'AUSTIN', ] ],
        'AUTOCAR'       => [
            'models' => [
                'AUTOCAR',
                'CAMION',
                'DC64B',
                'DC9364B',
                'S64TF12513',
                'BUSHMAN 200 196CC. MOTO',
            ]
        ],
        'B.S.A.'        => [ 'models' => [ ] ],
        'BARTOLETTI'    => [ 'models' => [ 'BARTOLETTI', ] ],
        'BEIBEN'        => [
            'models' => [
                'BEIBEN',
                '1624',
                '2542 S',
                '3138 K',
            ]
        ],
        'BLAC'          => [ 'models' => [ 'BLAC', ] ],
        'BMW'           => [
            'models' => [
                'F800',
                'MINI COOPER',
                'MOTOCICLETA',
                'MOTOCICLETA F650GS',
                'MOTOCICLETA R100- GS',
                'MOTOCICLETA R1200 GS',
                'MOTOCICLETA 500 CC. ADEL.',
                'M3',
                'M5',
                'XE-SALOON',
                'X1',
                'X1 XDRIVE25I',
                'X1 SDRIVE 18I',
                'X3',
                'X5',
                'X6',
                'Z3',
                '116I',
                '1181 - 5 TUERER',
                '120I',
                '135I COUPE',
                '2002 ADO 1975',
                '316',
                '318I',
                '320',
                '320A',
                '320I',
                '323I',
                '323IA',
                '325',
                '325I',
                '328I',
                '518',
                '520',
                '520I',
                '523I',
                '525I',
                '528IA',
                '528I',
                '535I',
                '635 CSI',
                '728',
                '728I',
                '735I',
                '750 IL',
                '330-X1A',
            ]
        ],
        'BOMBARDIER'    => [ 'models' => [ 'OUTLANDER MAX800', ] ],
        'BRAND'         => [ 'models' => [ 'BYD', ] ],
        'BRILLIANCE'    => [ 'models' => [ 'FRV', ] ],
        'BUCYRUS'       => [ 'models' => [ 'ERIE CCC - GRUA', ] ],
        'BUICK'         => [ 'models' => [ 'ABRAHAM', 'REGAL', ] ],
        'BYD'           => [
            'models' => [
                'FO 4X2',
                'FO-GI',
                'F3-R',
                '4X2',
            ]
        ],
        'C-Z'           => [ 'models' => [ 'REMOLQUE', ] ],
        'CADILLAC'      => [ 'models' => [ 'C-Z', 'ROLAND', ] ],
        'CAMC'          => [
            'models' => [
                'BROHAM',
                'DEVILLE',
                'EL DORADO',
                'ESCALADE',
                'HEARSE',
            ]
        ],
        'CAN-AM'        => [ 'models' => [ 'DUMPER', 'VOLQUETA 375', 'CUADRATRACK', ] ],
        'CF'            => [ 'models' => [ 'GENERAL', ] ],
        'CFMOTO'        => [ 'models' => [ '800-2 CUADRATRACK', ] ],
        'CHANA'         => [ 'models' => [ 'CUADRATRACK', ] ],
        'CHANGHE'       => [
            'models' => [
                'BENNI MINI',
                'SC7153A',
                'STAR',
            ]
        ],
        'CHATA'         => [
            'models' => [
                'MINIBUS',
                'CHATA',
                'GUERRA',
                'INDUSTRIA NACIONAL',
            ]
        ],
        'CHEVROLET'     => [
            'models' => [
                'FACE',
                'QQ3',
                'TIGGO',
                'YO - YO',
                'COLORADO',
            ]
        ],
        'CHRYSLER'      => [
            'models' => [
                'CHEVROLET',
                'A-20',
                'APACHE',
                'ASTRA',
                'ASTRO',
                'AVEO',
                'BEAUVILLE',
                'BLAZER',
                'BONANZA CUSTOM',
                'C-10',
                'C-20',
                'C-30',
                'C-3500',
                'C-40',
                'C-60',
                'CAMARO',
                'CAMIONETA D/C DLX',
                'CAPRICE',
                'CAPTIVA',
                'CARRYALL',
                'CAVALIER',
                'CELTA',
                'CHEVELLE',
                'CHEVETTE',
                'CHEVY',
                'CHEVY TRUCK',
                'CHEYENNE',
                'CHEYENNE CAMIONETA',
                'COLORADO',
                'COMODORO',
                'CORSA',
                'CORVETTE',
                'CRUZE',
                'D-20',
                'D-30',
                'D-60',
                'D-70',
                'DIPLOMATA',
                'DMAX',
                'EQUINOX',
                'EXPRESS',
                'GM14000',
                'IMPALA SEDAN LS',
                'KADET',
                'K2500',
                'LUMINA APV',
                'LUV',
                'MALIBU',
                'MARAJO',
                'MONTECARLO',
                'MONZA',
                'NOVA',
                'NPR',
                'NPR TURBO',
                'N300 MAX',
                'OMEGA',
                'PRINZ',
                'RODEO LS',
                'S-10',
                'SAIL',
                'SAIL Z NB LT',
                'SAVANA',
                'SEDAN',
                'SILVERADO',
                'SONIC',
                'SPORT VAN',
                'STACAS',
                'STAKES TRUCK',
                'STEPVAN',
                'SUBURBAN',
                'SUPER BRIGADIER',
                'SUPREMA',
                'TAHOE SPORT',
                'TRACKER',
                'TRAIL BLAZER',
                'TROOPER',
                'VECTRA GLS',
                'VERANEO',
                '600',
            ]
        ],
        'CITROEN'       => [
            'models' => [
                'CARAVAN 4X2',
                'CARAVAN 4X4',
                'GRAN CARAVAN LE 3.3',
                'NEON',
                'NEW PORT',
                'PT CRUISER',
                'PTCRUISER',
                'SEBRING',
                'SHADOWN 3000 CC',
                'STRATUS LX',
                'TOWN ',
                'VOYAGER',
                '300C',
                '300TTOURING',
            ]
        ],
        'COLES'         => [ 'models' => [ 'CITROEN', ] ],
        'CREAT'         => [ 'models' => [ '(CAMION GRUA)', ] ],
        'CUSTOM'        => [ 'models' => [ 'DANE - SEMIREMOLQUE', ] ],
        'DACIA'         => [ 'models' => [ 'BREAK', ] ],
        'DAEWOO'        => [
            'models' => [
                'CIELO',
                'DAMAS',
                'ESPERO',
                'LABO',
                'LANOS',
                'LEGANZA',
                'LEMANS',
                'MATIZ',
                'NEXIA',
                'NUBIRA',
                'PRICE',
                'RACER',
                'TICO',
            ]
        ],
        'DAIHATSU'      => [
            'models' => [
                'APPLAUSE',
                'BOON',
                'CHARADE',
                'CHARMANT',
                'CUORE',
                'DELTA',
                'FEROZA',
                'GRAN MOVI',
                'HIJET',
                'MIRA',
                'MOVE',
                'PYZAR',
                'ROCKY',
                'RUGGER',
                'SIRION',
                'STORIA',
                'TERIOS',
            ]
        ],
        'DAIMLER'       => [ 'models' => [ 'DAIMLER', ] ],
        'DAIMO'         => [ 'models' => [ 'DM150-11B', 'DM200', ] ],
        'DATSUN'        => [
            'models' => [
                'MINI',
                'PICK UP SIMPLE',
                '160J',
                '280 ZX',
            ]
        ],
        'DERBY'         => [ 'models' => [ 'SENDA', ] ],
        'DFM'           => [
            'models' => [
                'EQ1020TF',
                'EQ5021XXYF',
                'EQ6410LF',
            ]
        ],
        'DFSK'          => [ 'models' => [ 'DFSK', 'EQ 1020TF', ] ],
        'DIMEX'         => [
            'models' => [
                'VOLQUETA',
                '1721',
                '1725',
            ]
        ],
        'DNEPR'         => [ 'models' => [ 'MODELO : MT 11', ] ],
        'DODGE'         => [
            'models' => [
                'B4D400',
                'CALIBER',
                'CARAVAN',
                'CORONET',
                'CORQUEST',
                'D-700',
                'D-900',
                'DAKOTA',
                'DAKOTA CLUB 4X4',
                'DURANGO',
                'D4600 CAMION',
                'JOURNEY',
                'JOURNEY SXT',
                'MAGNUM',
                'NEON',
                'NITRO',
                'NITRO SLT SPORT',
                'OMNI',
                'POLARA',
                'RAIDER 2600 C.C.',
                'RAM',
                'RAM CHARGER',
                'RAM VAN B1500 4X2',
                'RAM VAN 4X2',
                'RAM 1500',
                'RAM 2500',
                'RAM 4X2',
                'RANGER',
                'SPIRIT',
                'STRATUS',
            ]
        ],
        'DONG'          => [
            'models' => [
                'FENG',
                'FENG JINGANG',
                'FENG RICH',
            ]
        ],
        'DORSEY'        => [ 'models' => [ 'DORSEY', ] ],
        'DUCATI'        => [
            'models' => [
                'DUCATI',
                'DIAVEL',
                'DIAVEL AMG',
                'DIAVEL CARBON',
                'DIAVEL CROMO',
                'DIAVEL RED',
                'HYPERMOTARD 1100',
                'HYPERMOTARD 1100 SP',
                'HYPERMOTARD 796',
                'MONSTER DIESEL',
                'MONSTER 696',
                'MONSTER 795',
                'MONSTER 795',
                'MULTISTRADA',
                'MULTISTRADA ABS',
                'MULTISTRADA 1200',
                'MULTISTRADA 1200 S SPRT',
                'MULTISTRADA 1200 S TOUR',
                'STREETFIGHTER S',
                'STREETFIGHTER 1100 S',
                'STREETFIGHTER 848',
                'SUPERBIKE 1198',
                'SUPERBIKE 1198 SP',
                'SUPERBIKE 1199 PANIGA S',
                'SUPERBIKE 1199 TRICOLOR',
                'SUPERBIKE 848',
                'SUPERBIKE 848 CORSE SE',
            ]
        ],
        'EAGLE'         => [ 'models' => [ 'SUMMIT', ] ],
        'EAM'           => [ 'models' => [ 'RANIPSTAR RC2CO', ] ],
        'ENGESA'        => [ 'models' => [ 'EE 25', ] ],
        'ESCORTS'       => [ 'models' => [ 'ESCORTS', 'RD 175', ] ],
        'EVOTRAK'       => [ 'models' => [ 'EVOTRAK', ] ],
        'FARGO'         => [
            'models' => [
                'D-300',
                'D-400',
                'D-500',
            ]
        ],
        'FENIX'         => [ 'models' => [ 'FX200-RX', ] ],
        'FERMI'         => [ 'models' => [ 'FERMI', ] ],
        'FERRARY'       => [ 'models' => [ 'FERRARY', ] ],
        'FIAT'          => [
            'models' => [
                'CAMION',
                'CAMION ESTACAS',
                'FIORINO',
                'FIORINO CAMIONETA',
                'IDEA',
                'LINEA ABSOLUTE',
                'MAREA',
                'MILLE',
                'OGGICE',
                'PALIO',
                'PALIO ADVENTURE',
                'PALIO KEEKEN VAGONETA',
                'PANORAMA',
                'PREMIO',
                'REGATTA',
                'SIENA',
                'STRADA',
                'TRACTOR FR645B',
                'UNO',
                '4000 CAMION',
            ]
        ],
        'FORD'          => [
            'models' => [
                'FORD',
                'AEROSTAR',
                'ASPIRE',
                'BRONCO II',
                'CARGO 1215',
                'CARRIER',
                'CLUB VAGONETA WAGON',
                'CONTOUR',
                'CONTOUR SE',
                'CORCEL II',
                'COUNTRY',
                'COURIER',
                'CUSTOM',
                'DEL REY',
                'DEL REY (VAGONETA)',
                'DIMEX 3030',
                'E-150',
                'E-350 SUPER VAN',
                'ECCO SPORT',
                'ECONOLINE',
                'ESCAPE',
                'ESCORT',
                'EXPEDITION',
                'EXPLORER',
                'F-B0',
                'F-100',
                'F-1000',
                'F-11000',
                'F-14000',
                'F-150',
                'F-250',
                'F-350',
                'F-379',
                'F-400',
                'F-4000',
                'F-450',
                'F-600',
                'F-600 (CAMION)',
                'F-700',
                'F-80',
                'F-914',
                'FAIRMONT',
                'FALCON',
                'FESTIVA',
                'FIESTA',
                'FOCUS',
                'FREESTART',
                'FREESTYLE',
                'GALAXIE',
                'GRANADA',
                'KA',
                'K74',
                'K744260',
                'L-8000',
                'LASER',
                'LINCOLN',
                'MERCURY CAPRI',
                'MERCURY TOPAZ',
                'MONDEO',
                'MUSTANG',
                'PAMPA',
                'PINTO',
                'PROBE',
                'RANCHERA',
                'RANGER',
                'RANGER CABINA Y MEDIA',
                'RANGER CABINA SENCILLA',
                'RANGER F-150',
                'RANGER XL',
                'SIERRA',
                'STYLESIDE CAMIONETA',
                'SUPER DUTY',
                'TAUNUS',
                'TAURUS',
                'TEMPO',
                'THUNDERBIRD',
                'TORINO',
                'TRANSIT',
                'U-50',
                'VERONA',
                'VERSALLES',
                'VICTORIA CROWN',
                'WILLIAMS',
                'WINDSTAR',
                'XL-150',
                '1600',
                '370 - 2 V - GASOLINA',
                '930 T',
            ]
        ],
        'FORLAND'       => [ 'models' => [ 'FORLAND', ] ],
        'FOTON'         => [
            'models' => [
                'FOTON',
                '(DIESEL) 4X2',
                'BJ1069VCJEA-D',
                'CAMION',
                'CAMION (GASOLINA)4X2',
                'CAMIONETA (GASOLINA)4X4',
                'CAMIONETA PICK UP',
                'CAMIONETA PICK UP DOBLE',
                'CAMIONETA T/DOBLE',
                'CAMIONETA T/SIMPLE',
                'OLLIN',
                '9320',
            ]
        ],
        'FREIGHTLINER'  => [
            'models' => [
                'CENTURY  CLASS',
                'COLUMBIA 120',
                'FL70',
            ]
        ],
        'FREUHAUF'      => [
            'models' => [
                ' SEMIRREMOLQUE',
                'SEMIREMOLQUE',
                'FRUEHAUF',
                'REMOLQUE',
            ]
        ],
        'FRV'           => [ 'models' => [ 'CROSS', ] ],
        'FULU'          => [ 'models' => [ 'MOTOR FLC3', ] ],
        'FURGON'        => [ 'models' => [ 'L300', ] ],
        'GAC'           => [ 'models' => [ 'GONOW TROY 100', ] ],
        'GAZ'           => [ 'models' => [ 'CAMION', ] ],
        'GEELY'         => [
            'models' => [
                'CK',
                'EC7',
                'EC7 (4X2)',
                'LC',
            ]
        ],
        'GEO'           => [ 'models' => [ 'STORM', ] ],
        'GMC'           => [
            'models' => [
                'C-20',
                'C-30',
                'CANYON',
                'JIMMY',
                'SLE SIERRA 5.700 CC.',
                'SUBURBAN',
                'VANDURA',
                'YUKON DENALI',
                '2000',
                '5000',
            ]
        ],
        'GMW'           => [ 'models' => [ 'DEER (SIN USO)', 'SAFE (SIN USO)', ] ],
        'GOLDEN'        => [ 'models' => [ 'DRAGON', ] ],
        'GOLDHOFER'     => [ 'models' => [ '4 EJES', ] ],
        'GREAT'         => [
            'models' => [
                'DANE REMOLQUE',
                'WALL DANE',
                'WALL DEER',
                'WALL FLORID',
                'WALL HAVAL',
                'WALL HAVAL H5',
                'WALL HAW 5',
                'WALL HOVER 2400 C.C.',
                'WALL SAFE',
                'WALL VOLEEX',
                'WALL VOLEEX C10',
                'WALL WINGLE',
                'WALL WINGLE 5',
            ]
        ],
        'GROVE'         => [ 'models' => [ 'AMERICANA (TRACTO CAMION)', 'TMS-375', ] ],
        'GUERRA'        => [ 'models' => [ 'GUERRA', 'REMOLQUE', ] ],
        'GWM'           => [ 'models' => [ 'HOVER', 'WINGLE', ] ],
        'HAFEI'         => [ 'models' => [ 'LUZUN', 'RUIYI', ] ],
        'HAIMA'         => [ 'models' => [ 'FSTAR', ] ],
        'HANOMAG'       => [ 'models' => [ 'HANOMAG', ] ],
        'HAOJIN'        => [ 'models' => [ 'HJ150-11', ] ],
        'HARLEY'        => [ 'models' => [ 'DAVIDSON CHOPER', 'DAVIDSON 1.100 CC.', ] ],
        'HEIL'          => [ 'models' => [ 'REMOLQUE', ] ],
        'HERCULES'      => [ 'models' => [ 'HERCULES', ] ],
        'HERO'          => [ 'models' => [ 'PUCH 70CC', ] ],
        'HIGER'         => [ 'models' => [ 'KLQ6129GC', ] ],
        'HINO'          => [
            'models' => [
                'HINO',
                'CISTERNA FS331S',
                'DUTRO',
                'FC142S',
                'FC144SA',
                'TRACTO CAMION',
                'TSD140-10',
                'VOLQUETA',
                'VOLQUETA FS331S',
                'VOLQUETA FS331SD',
                '1726',
                '500',
            ]
        ],
        'HONDA'         => [
            'models' => [
                'ACCORD',
                'ACTY (FURGONETA)',
                'ACURA',
                'ALPINE',
                'C-100',
                'C-90Z',
                'CARGO MOTOCICLETA',
                'CBR - 400 MOTOCICLETA',
                'CG-125',
                'CGL125',
                'CIVIC',
                'CR-V',
                'CRX',
                'CT 110',
                'CT 125',
                'CTX-200',
                'CT200',
                'DOMANI',
                'DOMINATOR 650 CC. MOTOCI',
                'FALCON',
                'FIT',
                'FOREMAN',
                'GOLDWING',
                'GRAND SPORTAGE',
                'H 100 S',
                'H 100SD',
                'INTEGRA',
                'JAZZ',
                'LEGEND',
                'MT 80',
                'NX-125',
                'ODYSSEY',
                'ORTHIA',
                'PARTNER',
                'PASSPORT',
                'PILOT',
                'PRELUDE',
                'QUINTET',
                'RAFAGA',
                'RANCHER',
                'RIDGELINE',
                'RINCON',
                'SHUTTLE',
                'SL 230 WU MOTOCICLETA',
                'SPACY',
                'STORM',
                'TITAN MOTOCICLETA',
                'TN-360-L',
                'TRAILL 110',
                'TRX 450',
                'TS 185 CC.',
                'VALLADE',
                'VARADERO',
                'WAVE',
                'WUYANG 125',
                'XL 125',
                'XL 185',
                'XL 185 S',
                'XL 200',
                'XL 250 S',
                'XL 600R',
                'XLR 125 CC.',
                'XR STANDARD',
                'XR 250',
                'XR 500 CC.',
                'XR 650',
                'XR-200',
                '100 CC.',
                '1000 CC.',
                '1200 CC.',
                '125 CC.',
                '150 CC.',
                '185 CC.',
                '200 CC.',
                '250 CC.',
                '350 CC.',
                '400 CC.',
                '450 CC.',
                '50 CC.',
                '500 CC.',
                '60 CC.',
                '600 CC.',
                '650 CC.',
                '750 CC.',
                '750 XRV',
            ]
        ],
        'HONLEI'        => [ 'models' => [ 'HL150GY-3A', ] ],
        'HUANGHAI'      => [ 'models' => [ 'DD1022M', ] ],
        'HUMMER'        => [
            'models' => [
                'H2',
                'AM GENERAL',
                'H3',
            ]
        ],
        'HUSABERG'      => [
            'models' => [
                'MOTO FE-450',
                'MOTO 125CC',
                'MOTO 150CC',
                'MOTO 175CC',
                'MOTO 200CC',
                'MOTO 300CC',
                'MOTO 350CC',
                'MOTO 400CC',
                'MOTO 450CC',
            ]
        ],
        'HYUNDAI'       => [
            'models' => [
                'ACCENT 1.3',
                'ACCENT 1.5',
                'ACCENT 1.5L 6774',
                'ATOS PRIME',
                'ATOS 1000 CC',
                'ATOS 4X2',
                'ATOZ VENTURE',
                'CHORUS',
                'COUNTRY',
                'ELANTRA',
                'EXCEL',
                'EXCEL GLS',
                'GALLOPER JEEP 2600',
                'GALLOPER VAGONETA 3000',
                'GETZ',
                'GRANDEUR',
                'GRASE',
                'H-100',
                'H-250 CAMIONETA',
                'H-350',
                'H-350 CAMION',
                'H-350 MINIBUS',
                'HD-72',
                'H1',
                'H1 AMBULANCIA',
                'H1 MINIBUS',
                'I-10',
                'I30',
                'MATRIX',
                'MIGHTY CAMION',
                'PONY',
                'PORTER',
                'SANTA FE',
                'SANTAMO',
                'SCOUPE',
                'SLD2Z-H100 2.0 CAMIONE',
                'SONATA',
                'STELLA',
                'STELLAR',
                'TERRACAN',
                'TIBURON',
                'TIBURON HD COUPE',
                'TUCSON',
                'VELOSTER',
                'VERA CRUZ',
                'VERNA',
            ]
        ],
        'IMSA'          => [ 'models' => [ 'IMSA', 'IM 125T', ] ],
        'INFINITI'      => [
            'models' => [
                'FX35',
                'QX56',
                'G20',
            ]
        ],
        'INTERNATIONAL' => [
            'models' => [
                'CAMION 12000',
                'CAMION 9300',
                'F5070',
                'LOADSTAR',
                'MODELO 9800',
                'PAYSTAR',
                'TRANSTAR',
                '1854 (PIRATA)',
                '2674',
                '4700',
                '4900',
                '7300',
                '9700',
            ]
        ],
        'ISUZU'         => [
            'models' => [
                'AMIGO',
                'AMIGO (SIN VIGENCIA)',
                'ASKA',
                'AXIOM',
                'BIGHORN',
                'CAMION',
                'CAMIONETA DOBLE CABINA',
                'CARIBE 4WD',
                'ELF 250',
                'FARGO',
                'FLAT DECK CAMIONETA',
                'FSR',
                'GEMINI',
                'HIDROVAC FTR',
                'JMC',
                'JOURNEY',
                'KAZOLA',
                'MISTERIOUS UTILITY',
                'NKR',
                'NPC7SP',
                'NPR',
                'PIAZZA',
                'PICK UP',
                'RODEO',
                'STYLUS',
                'TROOPER',
                'VEHICROSS',
                'WFR',
                'WIZARD',
            ]
        ],
        'ITASA'         => [ 'models' => [ 'FLAMENGO', ] ],
        'IVECO'         => [
            'models' => [
                'IVECO',
                'DAILY',
                'F1015',
                'MLC120F18',
                'MLC150E18K',
                'MLL150E18',
                'OTOYOL',
                '190.26',
                '190GHT',
                '35-10V  4 X 4',
                '59.12',
                '59.12 S',
                '619-N1B',
                '65-12 CAMION',
                '8140',
            ]
        ],
        'JAC'           => [
            'models' => [
                'JAC',
                'A137 SEDAN',
                'A137 Y A138',
                'B CROSS',
                'B SEDAN LUXURY',
                'B-CLASS',
                'B-CROSS LUXURY',
                'HFC1042K2T',
                'HFC1083KR1',
                'J3 TURIN',
                'J5',
                'REFINE',
                'REIN ESTANDAR',
                'URBAN',
            ]
        ],
        'JAGUAR'        => [
            'models' => [
                'S TYPE',
                'S X-TYPE',
                'VANDEN PLAS',
                'XJ',
            ]
        ],
        'JAWA'          => [ 'models' => [ '265', '350', ] ],
        'JBC'           => [ 'models' => [ 'CAMION CIL 4752', ] ],
        'JCB'           => [ 'models' => [ 'CAMION', ] ],
        'JEEP'          => [
            'models' => [
                'JEEP',
                'CHEROKEE SPORT',
                'CHEROKEE 2500CC',
                'CHEROKEE 2800 CC',
                'CHEROKEE 4000CC',
                'CHEROKEE 5200CC',
                'COMANCHE',
                'COMMANDER',
                'COMPASS',
                'GRAND CHEROKEE',
                'GRAND CHEROKEE COUNTRY',
                'GRAND CHEROKEE LAREDO',
                'GRAND CHEROKEE LIMITED',
                'KORANDO',
                'LAREDO',
                'LIBERTY',
                'PATRIOT',
                'PIONEER',
                'RENEGADE',
                'SAHAARA',
                'WAGONEER',
                'WAGONEER (CAMIONETA)',
                'WILLYÂ´S',
                'WRANGLER',
            ]
        ],
        'JIALING'       => [ 'models' => [ 'JH-125L', ] ],
        'JIEFANG'       => [ 'models' => [ '141K2', ] ],
        'JIN'           => [
            'models' => [
                'BEI',
                'BEI BRILLIANCE FSV 1500CC',
                'BEI HAISE',
            ]
        ],
        'JINCHENG'      => [ 'models' => [ 'HIACE', ] ],
        'JMC'           => [ 'models' => [ 'JX1021PSD3', 'JX1032D', ] ],
        'JOBA'          => [ 'models' => [ 'PAMAPA', ] ],
        'JOHN DEERE'    => [
            'models' => [
                'SLC 6200',
                '6600',
                '2850',
                '3040 ',
                'D85-A-21',
                'D85A',
                '7630 4X4 S100',
                'D4E',
                'D8K',
            ]
        ],
        'JUVE'          => [ 'models' => [ 'JH-100', ] ],
        'KAISER'        => [ 'models' => [ 'TRUCK', ] ],
        'KAMAZ'         => [
            'models' => [
                'MOD-55111',
                '53212',
                '5325',
                '54112',
            ]
        ],
        'KANDA'         => [ 'models' => [ 'KD150-1113', ] ],
        'KANDUS'        => [ 'models' => [ 'KANDUS', ] ],
        'KARZ'          => [ 'models' => [ 'KARZ', ] ],
        'KATO'          => [ 'models' => [ 'KR-250', ] ],
        'KAWASAKI'      => [
            'models' => [
                'BRUTE FORCE',
                'CONCORUS',
                'KC-90',
                'KE-125',
                'KLR-250',
                'KLR-600',
                'KRF 750',
                'KVF650-AI',
                'MOTOCICLETA',
            ]
        ],
        'KEN'           => [ 'models' => [ 'WORT', 'WORT C-500', ] ],
        'KENWORTH  '    => [ 'models' => [ 'T-600', ] ],
        'KENYO'         => [ 'models' => [ 'F150', ] ],
        'KESTONE'       => [ 'models' => [ 'RAPTOR', ] ],
        'KIA'           => [
            'models' => [
                'AVELLA',
                'BESTA',
                'BONGO',
                'CAPITAL',
                'CARENS',
                'CARNIVAL',
                'CERES',
                'CLARUS',
                'COMBI.',
                'COSMOS',
                'CREDO II',
                'DELTA',
                'K-2400',
                'K-2700',
                'K-3500',
                'K-3600',
                'K-3600S',
                'MOHAVE',
                'MOTORS',
                'OPTIMA',
                'PARKTOWN',
                'PICANTO',
                'PREGIO',
                'PRIDE',
                'RIO',
                'ROCSTA',
                'SEDONA',
                'SEPHIA',
                'SHUMA',
                'SORENTO EX',
                'SOUL',
                'SPORTAGE',
                'TOPIC',
                'TOWNER ASIA',
                'WIDE BONGO',
            ]
        ],
        'KIMCO'         => [ 'models' => [ 'VENOX 250', ] ],
        'KIN'           => [ 'models' => [ 'ROAD XT200GY', ] ],
        'KINGO'         => [ 'models' => [ 'KG150-15', ] ],
        'KLIA'          => [ 'models' => [ 'CA-200', 'M-160', ] ],
        'KORA'          => [ 'models' => [ 'GC-125', ] ],
        'KRONE'         => [ 'models' => [ 'SEMIREMOLQUE', ] ],
        'KTM'           => [ 'models' => [ '350 SX-F', '600', ] ],
        'KUMOTO'        => [ 'models' => [ 'XF 125 A', '125 A', ] ],
        'KYGO'          => [ 'models' => [ 'SG125', ] ],
        'KYMKO'         => [
            'models' => [
                'CK 125',
                'KG 150-3',
                'KG125',
            ]
        ],
        'LADA'          => [
            'models' => [
                'N I V A',
                'S A M A R A',
                '1500',
                '2103',
                '2107',
            ]
        ],
        'LANCE'         => [ 'models' => [ '400SC', ] ],
        'LAND'          => [
            'models' => [
                'ROVER',
                'ROVER DEFENDER 110',
                'ROVER DISCOVERY',
                'ROVER EVOQUE',
                'ROVER FREELANDER',
                'ROVER RANGE ROVER',
            ]
        ],
        'LEIKE'         => [ 'models' => [ 'LK-125', ] ],
        'LEOPARD'       => [ 'models' => [ '  MT-200-20', ] ],
        'LEXUS'         => [ 'models' => [ 'ES330', ] ],
        'LICENE'        => [ 'models' => [ 'LICENE', ] ],
        'LIESS'         => [ 'models' => [ 'LIESS', ] ],
        'LIFAN'         => [
            'models' => [
                'CG-125',
                'FOISON MINIBUS',
                'LF-CARGO VAN',
                'LF-FOISON MINIBUS',
                'LF-MINI TRUCK',
                'LF-X-60',
                'LF-320',
                'LF-520',
                'LF-520I',
                'LF-620',
                'LF1022',
                'PICKUP DX 1299CC',
                'SEASON',
                'USM 250',
                'VAN DX',
                'X6',
                '120 MINIBUS',
                '320',
                '520',
                '520I',
            ]
        ],
        'LINCOLN'       => [
            'models' => [
                'CONTINENTAL',
                'MKX',
                'NAVIGATOR',
            ]
        ],
        'LONCIN'        => [ 'models' => [ 'LX125-2', ] ],
        'LORAIN'        => [ 'models' => [ '(GRUA)', ] ],
        'MACK'          => [ 'models' => [ 'MACK', 'PLUMA', ] ],
        'MAHINDRA'      => [ 'models' => [ 'PICK UP', 'PICKUP', ] ],
        'MAN'           => [ 'models' => [ 'MAN', '(INDUSTRIAL)', ] ],
        'MARTIN'        => [
            'models' => [
                'MARTIN',
                'MT200-GY3',
                'AUTO 800',
                'BOSS-200',
                'CAMIONETA 4X4 1000',
                'TRC',
            ]
        ],
        'MAS'           => [ 'models' => [ 'VOLQUETA', ] ],
        'MASSEY'        => [ 'models' => [ 'FERGUSON PALA CARGADORA', 'FERGUSON 296', ] ],
        'MAZDA'         => [
            'models' => [
                'AXELA 2004 4X2 CC1500',
                'B-2000',
                'B-2200I',
                'B-2500',
                'B-2600',
                'B-2900',
                'B-3000',
                'BONGO',
                'BONGO BRAWNY',
                'BT-50',
                'CAMION T-45',
                'CAPELLA',
                'CX-9',
                'DEMIO',
                'E-2000',
                'FAMILIA',
                'GT-X',
                'HATCHBACK',
                'MARVIE',
                'MIATA',
                'MILENA',
                'MPV',
                'MPV.4DR VAGONETA',
                'MX-3',
                'MX-6',
                'PICK UP P2500',
                'PREMACY',
                'PROCEEDE LEVANTE',
                'PROTEGE 5',
                'TITAN 4X2',
                'TRIBUTE DX',
                'UK51 EAS CAMIONETA',
                'VERIZA',
                '2',
                '3 SPORT',
                '3 4X2',
                '323',
                '323GLX',
                '61',
                '626',
                '929',
            ]
        ],
        'MERCEDES BENZ' => [
            'models' => [
                'MERCEDES BENZ',
                'A-160',
                'ATEGO',
                'C-220',
                'C-230T',
                'CLK',
                'CLS 500 COUPE',
                'CROSS COUNTRY',
                'E-320',
                'ELEGANCE',
                'ELEGANCE E-230',
                'G-320 JEEP',
                'GCLAS G500 G-55D',
                'KOMPRESSOR',
                'L-1618/51',
                'L-708E/35',
                'L-912/42.5',
                'L-914/42.5',
                'LA-1418/51 4X4',
                'LS-1630/45',
                'M 270 CDI',
                'MB- 140',
                'ML-230',
                'ML-320',
                'ML350',
                'ML430',
                'OF1620 OMNIBUS',
                'PUCH GE 230',
                'ROADSTER AVG/94',
                'S-280',
                'S-320',
                'S-430',
                'SAURER',
                'SL-500',
                'SLK',
                'SLK-200',
                'SMART',
                'SPRINTER',
                'S420 L',
                'UNIMOG',
                'VIALE',
                '1113',
                '1118',
                '1218',
                '1418',
                '1516',
                '1520',
                '1618',
                '1718/48',
                '190',
                '190 E',
                '1935',
                '1935-INTERCULER',
                '1941 INTERCOOLER',
                '200',
                '220',
                '230',
                '230 (VAGONETA)',
                '230 E',
                '230 SL',
                '230-CE COUPE',
                '2318',
                '240E',
                '250',
                '260E',
                '280',
                '280 GE',
                '280 SE',
                '280 SEL',
                '290 E',
                '300',
                '300 SE',
                '300 SL',
                '300E',
                '380 SEL',
                '380 SL',
                '430E',
                '450 SE',
                '450 SL',
                '500 S',
                '500 SEL',
                '560 SEL',
                '912',
                '912 (CAMIONETA)',
            ]
        ],
        'MERCURY'       => [ 'models' => [ 'MOUNTAINEER SV', 'VILLAGER', ] ],
        'MG'            => [ 'models' => [ 'MG', 'SPORT', ] ],
        'MICHIGAN'      => [ 'models' => [ 'PALA FRONTAL', ] ],
        'MIDGET'        => [ 'models' => [ 'SEDAN 2.300 CC.', ] ],
        'MINI'          => [ 'models' => [ 'COOPER', 'COOPER S', ] ],
        'MISNO'         => [ 'models' => [ 'CHOOPER', ] ],
        'MITSUBISHI'    => [
            'models' => [
                'MITSUBISHI',
                'MODELO IO',
                'ASX',
                'CANTER',
                'CHALLENGER',
                'CHARIOT',
                'COLT',
                'CORDIA',
                'DELICA 4X4',
                'DIAMANTE',
                'DION',
                'DION EXCEED',
                'DOBLE CABINA 4WD',
                'DODGE RAIDER',
                'ECLIPSE',
                'ENDEAVOR',
                'ETERNA',
                'EXPO LEV SPORT',
                'FIGHTER',
                'FTO',
                'FUSO',
                'FUSO 4 TON.',
                'GALANT',
                'GALANT SUPER SALOON',
                'GALOPER',
                'GRANDIS',
                'GT 300',
                'HD COUPE TIBURON',
                'L-1600',
                'L-300 XL',
                'L-400 XL',
                'LANCER',
                'LANCER (VAGONETA)',
                'LEGNUM',
                'LIBERO',
                'L200',
                'L200-TRITON',
                'MIRAGE',
                'MONTERO',
                'MONTERO DESDE 1991',
                'MONTERO HASTA 1990',
                'MONTERO IO',
                'MONTERO SPORT',
                'MONTERO TOPGLX 2.4',
                'MONTERO 2600 C.C.',
                'N-J54',
                'NATIVA',
                'OUTLANDER',
                'PAJERO',
                'PAJERO IO',
                'PAJERO JR',
                'PAJERO MINI',
                'PIC-WIC',
                'PICKUP',
                'RAIDER',
                'RAIDER JEEP',
                'ROSA DELUXE - DIE',
                'RVR',
                'SAPPORO',
                'SIGMA',
                'SPACE GEAR',
                'SPACE RUNNER GLX',
                'SPACE WAGON',
                'SPACE WAGON GLX',
                'SRV',
                'STATION WAGON',
                'SUMMIT',
                'TREDIA',
                'TRITON',
                'TURBO CANTER',
                'TWIN TURBO - 3000',
            ]
        ],
        'MIZUMO'        => [
            'models' => [
                'MIZUMO',
                'SIMPLE',
                'SIMPLE 125',
                'SIMPLE 200',
                'SIMPLE 250',
                'SIMPLE 350',
            ]
        ],
        'MONTENEGRO'    => [ 'models' => [ 'ACOPLADO', 'SBU2', ] ],
        'MONTERO'       => [ 'models' => [ 'MT 150', 'MT125 B1SS', 'MT250', ] ],
        'MOTO'          => [
            'models' => [
                'MOHERO PUCH',
                'JIAILING',
                'MONTERO MT250-2',
                'GUZEL',
            ]
        ],
        'MUDAM'         => [ 'models' => [ 'MD MICROBUS', ] ],
        'MUSSO'         => [ 'models' => [ 'GUZEL', ] ],
        'NISSAN'        => [
            'models' => [
                'NISSAN',
                'AD WAGON',
                'ALMERA XGL',
                'ALTIMA',
                'ARMADA',
                'ATLAS',
                'AVENIR',
                'AXXESS',
                'BLUE-BIRD',
                'CABINA SENCILLA',
                'CABSTAR',
                'CAFIRO',
                'CALIFORNIA',
                'CAMIONETA PICK-UP 4X2',
                'CARAVAN',
                'CEDRIC',
                'CIVILAN',
                'CIVILIAN',
                'CONDOR',
                'CONDOR TURBO',
                'D-21',
                'DX',
                'ELGRAND',
                'EX SALOON',
                'EXPERT',
                'FIERA',
                'FIERA 4X4',
                'FRONTIER',
                'FRONTIER 4X4',
                'HOMY',
                'CHYVAN',
                'INFINITI',
                'JUKE',
                'JUKE FL-006',
                'JUNIOR',
                'KING CAB',
                'LARGO',
                'LATIO',
                'LAUREL',
                'LIBERTY',
                'LUCINO',
                'L4-807',
                'MARCH',
                'MAXIMA',
                'MERCURY VILLAGER',
                'MINI',
                'MISTRAL',
                'MKB21',
                'MURANO',
                'NAVARA',
                'NOTE',
                'PATHFINDER',
                'PATROL',
                'PICK UP CABINA SENCILLA',
                'PICK UP D/C',
                'PLATINA',
                'PRAIRE',
                'PRESEA',
                'PRESEA 1800 CC',
                'PRIMERA CAMINO',
                'PRIMERA GXE',
                'PRIMERA 4X2',
                'PULSAR',
                'QASHQAI',
                'QUEST',
                'REGULUS',
                'RNESSA',
                'ROGUE',
                'SAFARI',
                'SEDAN',
                'SENTRA',
                'SENTRA II',
                'SERENA',
                'SILVIA',
                'SKYLINE',
                'STANZA',
                'SUNNY',
                'SUPER SALOON',
                'T-135',
                'TEANA',
                'TERRANO',
                'TIIDA',
                'TITAN',
                'TSUBAME',
                'TSUBAME (VAGONETA)',
                'UD',
                'URVAN',
                'VANETTE',
                'VERSA',
                'VOLQUETA',
                'WINGROAD',
                'X-TRAIL',
                'XTERRA',
                'XTRAIL',
                'XTREMEI',
                'Z350',
                '200XR TURBO',
                '3002X',
                '350Z 4X2"',
                '4 WD DOBLE CABINA',
                'PATROL DESDE 1991 HASTA 1990',
            ]
        ],
        'NIVA'          => [ 'models' => [ 'NIVA', ] ],
        'OLDSMOBILE'    => [ 'models' => [ 'BRAVADA', 'TORNADO', ] ],
        'OPEL'          => [
            'models' => [
                'ASTRA A6',
                'KADETT',
                'REKORD',
            ]
        ],
        'OPELVITA'      => [ 'models' => [ 'OPELVITA', ] ],
        'OSHKOSH'       => [ 'models' => [ 'CAMION', ] ],
        'PEGASSO'       => [
            'models' => [
                'PEGASSO',
                'CG125',
                'KTX 250',
                'KT150',
            ]
        ],
        'PETERBILT'     => [ 'models' => [ 'TRUCK', ] ],
        'PETROMIN'      => [ 'models' => [ 'PETROMIN', ] ],
        'PETTIBONE'     => [ 'models' => [ 'PETTIBONE', ] ],
        'PEUGEOT'       => [
            'models' => [
                '106XT',
                '205',
                '206',
                '306',
                '307 XTP',
                '307XR',
                '405',
                '405 GL',
                '406',
                '504',
                '505',
                '806',
            ]
        ],
        'PIAGGIO'       => [ 'models' => [ 'VESPA', ] ],
        'PLYMOUTH'      => [
            'models' => [
                'BREEZE',
                'COLT',
                'HORIZON',
                'VOYAGER',
            ]
        ],
        'POLARIS'       => [
            'models' => [
                'CUADRATRACK RZR 900',
                'QUADRA TRACK MAGNUN4X4',
                'QUADRA TRACKBIGBOSS6X6',
                'SIXTRACK-BIG BOC',
                'PONTIAC',
                'FIERO',
                'FIREBIRD',
                'GRAND AM',
                'LE MANS',
            ]
        ],
        'PORSCHE'       => [ 'models' => [ 'PORSCHE', 'CAYENNE', ] ],
        'PUMA'          => [ 'models' => [ 'PU150-11', ] ],
        'QUE'           => [ 'models' => [ 'MOTO', ] ],
        'RANDON'        => [ 'models' => [ 'RANDON', 'REMOLQUE', ] ],
        'RANGE'         => [ 'models' => [ 'ROVER', 'MINO', ] ],
        'REMOLQUE'      => [ 'models' => [ 'REMOLQUE', ] ],
        'RENAULT'       => [
            'models' => [
                'CBH280 VOLQUETA',
                'CLIO',
                'CLIO HATHBACK',
                'DUSTER EXPRESSION 4X2',
                'FUEGO',
                'GBH',
                'KANGOO EXPRESS',
                'KOLEOS',
                'KOLEOS DINAMIQUE AT2.5',
                'KOLEOS DYNAMIQUE',
                'LAGUNA',
                'MEGANE',
                'R-18GTX',
                'SANDERO',
                'SCENIC',
                'STEPWAY',
                'SYMBOL AUTENTIQUE',
                'SYMBOL EXPRESSION',
                'TRAFIC TA-52',
                'TXE',
                'VAGONETA SEDAM',
                '5 GTL',
                '9 GTL',
            ]
        ],
        'REO'           => [ 'models' => [ 'CAIMAN', ] ],
        'RUDO'          => [ 'models' => [ 'RD200 3X2', 'XY200GYII-D', ] ],
        'SAAB'          => [ 'models' => [ 'SAAB', ] ],
        'SALTO'         => [ 'models' => [ '(CHATA)', ] ],
        'SAMSUNG'       => [ 'models' => [ 'MODELO SV-110', 'SV 110', ] ],
        'SATECI'        => [ 'models' => [ 'SEMIREMOLQUE', ] ],
        'SATURN'        => [ 'models' => [ 'SL1', 'STATION WAGON', ] ],
        'SAURER'        => [ 'models' => [ 'SAURER', ] ],
        'SCANIA'        => [
            'models' => [
                'SCANIA',
                'G420',
                'K380',
                'R124',
                'T-112 E.',
                'VABIS',
                '110 SUPER A DIESEL',
                '112 H',
                '113 E CAMION',
                '113 H CAMION',
                '114 G',
                '124G - 360 CAMION',
                '319',
            ]
        ],
        'SCHERTZER'     => [ 'models' => [ 'SCHERTZER', ] ],
        'SCHEUERLE'     => [ 'models' => [ 'SCHEUERLE', ] ],
        'SCHIFER'       => [ 'models' => [ 'SEMIREMOLQUE', ] ],
        'SCION'         => [ 'models' => [ 'XD', ] ],
        'SEAT'          => [
            'models' => [
                'CORDOBA VARIO 1.6 SXE',
                'CORDOBA 1.6 SXE',
                'CORDOVA CLX',
                'CORDOVA CLX 1.8',
                'IBIZA',
                'IBIZA CLX',
                'IBIZA GLX',
                'IBIZA GTI',
                'IBIZA 1.4 SE',
                'INCA 1.4 VAN (FURGONETA)',
                'LEON 2.0',
                'TOLEDO GLX',
                'TOLEDO GTI',
            ]
        ],
        'SHINERAY'      => [ 'models' => [ 'SY6370', ] ],
        'SHININGMOTOR'  => [ 'models' => [ 'FX-250ZH', ] ],
        'SKODA'         => [ 'models' => [ 'LAVORIT L-135', 'OCTAVIA', ] ],
        'SKYGO'         => [ 'models' => [ 'SG125 GY', 'SG200GY-2', ] ],
        'SPVS'          => [ 'models' => [ 'SIN USO - DATSUN', 'SIN USO - MITSUBISHI', ] ],
        'SSANG'         => [
            'models' => [
                'YOUNG',
                'YOUNG KENWORTH',
                'YOUNG KORANDO',
                'YOUNG MUSSO',
            ]
        ],
        'STERLING'      => [ 'models' => [ '7500', ] ],
        'STEYR'         => [ 'models' => [ 'ZZ3322', ] ],
        'STUDEBAKER'    => [ 'models' => [ 'CAMION', ] ],
        'SUBARU'        => [
            'models' => [
                'BAJA',
                'B9 TRIBECA',
                'COUPE 1800 TURBO ALLRAD',
                'DOMINGO',
                'E-10',
                'E12 4WD',
                'FORESTER',
                'GL',
                'IMPREZA',
                'IMPREZA  (VAGONETA)',
                'J 10 4WD GL',
                'J 12 4WD GL',
                'JUSTY E-10',
                'JUSTY E/12',
                'J12',
                'L',
                'LEGACY',
                'LEGACY (VAGONETA)',
                'M-80',
                'MV CAMIONETA',
                'OUTBACK STW 2.5 AWD 4X4',
                'RX (TURBO)',
                'SRX 1.6',
                'XT-TURBO',
                '1.6 DL',
            ]
        ],
        'SUKIDA'        => [ 'models' => [ 'SK150', ] ],
        'SUMO'          => [ 'models' => [ 'BRAHO 150', ] ],
        'SUPER'         => [ 'models' => [ 'MOTO SM200GY-6', 'MOTOS', ] ],
        'SUZUKI'        => [
            'models' => [
                'I10',
                'AERIO',
                'AERIO SEDAN',
                'ALTO',
                'ALTO DLX',
                'ALTO K10',
                'APB',
                'APV',
                'APV CARRY',
                'APV PANEL VAN',
                'APV PICK UP',
                'B-120 N MOTOCICLETA',
                'BALENO',
                'CARRY',
                'CELERIO',
                'CELERIO AT',
                'CHEVROLET CRUZE',
                'COUPE',
                'CULTUS',
                'DF-200 EX MOTOCICLETA',
                'DL-1000 MOTOCICLETA',
                'DR 200 MOTOCICLETA',
                'DR 650 MOTOCICLETA',
                'DR-125',
                'EN125/2A MOTOCICLETA',
                'EQUATOR 4X2',
                'ER 185 MOTOCICLETA',
                'ESCUDO',
                'ESTEEN GLX',
                'FB-100 MOTOCICLETA',
                'FD110 MOTOCICLETA',
                'FORENZA',
                'FORZA',
                'GEO TRACKER',
                'GN125',
                'GRAND VITARA',
                'GSX BIKIN',
                'IGNIS',
                'INTRUDEA',
                'JAC',
                'JIMMY',
                'KINGQUAD',
                'LTF 4WD 246CC. CUADRA',
                'MARUTI',
                'METRO',
                'PICK  UP',
                'RASHEEN',
                'SAMURAI',
                'SANTANA',
                'SIDEKICK',
                'SIDEKYNG',
                'SJ 413',
                'SJ410',
                'SJ413 UTX',
                'SJ413 VXT',
                'SJ413-JX',
                'SNA413VXPS JIMNY',
                'SOLIO',
                'SUPER CARRY',
                'SWIFT',
                'SX4',
                'SX4 SEDAM',
                'TF-125',
                'TRACKER',
                'TS-185 MOTOCICLETA',
                'V-STROM DL',
                'VAGON R',
                'VERONA 4X2',
                'VITARA',
                'VITARA X90',
                'WAGON R 4 X 2',
                'VOLUCIA',
                'WAGON R 4 X 4',
                'XL-7',
                '183',
                '200 SX',
                'ALPINE',
            ]
        ],
        'TATA'          => [
            'models' => [
                'MOD 608 4434 CC.',
                'SIERRA VAGONETA',
                '1313',
                '207',
                '909/36',
            ]
        ],
        'TERMOQUIN'     => [ 'models' => [ 'FRIGORIFICO', ] ],
        'TILLVERKARE'   => [ 'models' => [ 'TILLVERKARE', ] ],
        'TOYOTA'        => [
            'models' => [
                'TOYOTA',
                'ACE G15',
                'BANDEIRANTE',
                'CALDINA',
                'CAMRY',
                'CARIB',
                'CARINA',
                'CELICA',
                'CERES',
                'COASTER',
                'COROLLA',
                'CORONA',
                'CORONA (VAGONETA)',
                'TOYOTA',
                'ACE G15',
                'BANDEIRANTE',
                'CALDINA',
                'CAMRY',
                'CARIB',
                'CARINA',
                'CELICA',
                'CERES',
                'COASTER',
                'COROLLA',
                'CORONA',
                'CORONA (VAGONETA)',
                'CORSA',
                'CRESSIDA',
                'CRESTA',
                'CROWN',
                'CROWN SUPER SALOON',
                'CURREN',
                'CYNOS',
                'DA 115L/H3',
                'DUET',
                'DYNA',
                'ECHO',
                'EMINA',
                'ESTIMA',
                'FA-100',
                'FJ-CRUISER',
                'FUNCARGO',
                'GAIA',
                'GRANVIA',
                'GRANVIA (VAGONETA)',
                'GREEN S',
                'HIACE',
                'HIGHLANDER',
                'HILUX',
                'HILUX DC',
                'HILUX SURF',
                'IPSUM',
                'IST',
                'JEEP',
                'JEEP BL',
                'LAND CRUISER',
                'LAND CRUISER DESDE 1991',
                'LAND CRUISER HASTA 1990',
                'LAND CRUISER PRADO',
                'LAND CRUISER STATION W',
                'LEVIN 1600 CC',
                'LEXUS.',
                'LITE ACE',
                'LITE ACE NOAH',
                'LUCIDA',
                'MARINO',
                'MARK II',
                'MATRIX XR',
                'MR2',
                'NADIA',
                'PASEO',
                'PASSO',
                'PICK UP',
                'PLATZ',
                'PRADO',
                'PREVIA',
                'PROBOX',
                'RAUM',
                'RAV 4 ADVANTAGE',
                'RAV4',
                'SCION TC 2400 CC  4X2',
                'SEQUOIA',
                'SERA',
                'SIENNA',
                'SPACIO',
                'SPIDER',
                'SPRINTER CARIB',
                'SPRINTER MARINO',
                'SPRINTER SE-VINTAGE',
                'SPRINTER TRUENO',
                'SPRINTER XE-VINTAGE',
                'STARLET',
                'STARLET PARTICULAR',
                'STATION WAGON',
                'STOUT',
                'SUPRA',
                'T-100',
                'T/100 CAMIONETA',
                'TACOMA',
                'TERCEL',
                'TOURING',
                'TOWNACE',
                'TOYOACE',
                'TRUENO',
                'TUNDRA',
                'VIOS',
                'VISTA ARDEO D4',
                'VITZ',
                'VOLQUETA',
                'WISH',
                'YARIS',
                '4 RUNNER',
            ]
        ],
        'TRANSCRAFT'    => [ 'models' => [ 'THO-40', ] ],
        'TRINPH'        => [ 'models' => [ 'TR6', ] ],
        'TRIUMPH'       => [ 'models' => [ 'TIGER 4X2', ] ],
        'TRX'           => [ 'models' => [ 'FOREMAN CAMION', ] ],
        'UM-100-B'      => [ 'models' => [ 'MOTOCICLETA', ] ],
        'URAL'          => [ 'models' => [ 'MOTOCARD', ] ],
        'USM'           => [
            'models' => [
                'USM',
                'CG 125',
                'MOTOCARRO',
                'XF PACKAGE',
                '100 4x2',
                '150 4X2',
                '200 4X2',
                '250 4x2',
                '4X2',
            ]
        ],
        'VALMET'        => [ 'models' => [ '118', '1280', ] ],
        'VESPA'         => [
            'models' => [
                'ET4',
                'GTV 250',
                'LX 150',
            ]
        ],
        'VIBERTY'       => [ 'models' => [ 'VIBERTY', ] ],
        'VICTORY'       => [ 'models' => [ 'CRUISER-V92C', 'SL-6600', ] ],
        'VOLGA'         => [ 'models' => [ 'GAZ', ] ],
        'VOLKSWAGEN'    => [
            'models' => [
                'VOLKSWAGEN',
                'AMAROK',
                'AMAZON',
                'APOLO',
                'BORA',
                'BRASILIA',
                'CABRIOLET',
                'CADDY',
                'CAMION 10-150',
                'CAMION 35-300',
                'COMBI',
                'CROSSFOX',
                'DOBLE CABINA',
                'ESCARABAJO',
                'FOX',
                'FUSCA',
                'GOL',
                'GOL PICKUP',
                'GOLF',
                'GOLF COUNTRY',
                'JETTA',
                'KARMAN GHIA',
                'LOGUS',
                'MULTIVAN',
                'NEW BEETLE',
                'PARATI',
                'PASSAT',
                'PETA',
                'PICK UP 261',
                'POLO',
                'POLO HATCH',
                'POLO SEDAN',
                'QUANTUM.',
                'RABBIT',
                'SAFARI TIPO JEEP',
                'SANTANA',
                'SAVEIRO CAMIONETA',
                'SEDAN',
                'SIMPLE',
                'SIRROCO',
                'TIGUAN',
                'VARIANT 1600',
                'VENTO',
                'VOYAGE',
                'WORKER',
                '11-130',
                '110-S',
                '13-190',
                '14-140',
                '15-190',
                '17-220',
                '17-220 WORKER',
                '31.310',
                '6-140',
                '6-80',
                '7-110-S',
                '7-110S',
                '7-140',
                '7-905',
                '8-100',
                '8-120',
                '8-140',
                '8150',
            ]
        ],
        'VOLVO'         => [
            'models' => [
                'VOLVO',
                'F-16',
                'FH-12',
                'FH-13',
                'FH16',
                'FL-12',
                'VNL',
                'VNL-670',
                'B-40',
                'B-50',
                'C 202',
                'F-10 CAMION',
                'F-12',
                'F-7',
                'F-89',
                'F6-16',
                'INTERCOOLER',
                'N-10',
                'N-1027',
                'N-12',
                'N-720',
                'NL - 10 CAMION',
                'NL - 12 360 CAMION',
                'NL10-340',
                'NL12-360',
                'S-70',
                'S-90',
                'SH12420',
                'V-70XC',
                'VNL610',
                'VNL64T',
                'VNM64',
                'VOLAT',
                'XC90',
                '240 DL',
                '240 GL',
                '240 GLE',
                '240-GL',
                '244',
                '244 GL',
                '244 GLE',
                '245 GL',
                '264 GLE',
                '265 GL',
                '360GL',
                '440 GLT',
                '540',
                '740',
                '760GLE',
                '780',
                '850 GL',
                '850 TURIM',
                '940 GL',
                '960',
            ]
        ],
        'WHITE'         => [ 'models' => [ 'ROAD BOSS', 'ROAD COMMANDER 2', ] ],
        'WHITEGMC'      => [ 'models' => [ 'CONVENTIONAL 4X2', ] ],
        'WULING'        => [
            'models' => [
                'WULING',
                'LZW 1010 PSN',
                'LZW 5010 XXYNE',
                'LZW 6360',
                'PICK UP PINEI',
            ]
        ],
        'WUYANG'        => [ 'models' => [ 'WY150-12', ] ],
        'XINGYVE'       => [ 'models' => [ 'XINGYUE', ] ],
        'XINKAI'        => [ 'models' => [ 'HXK1021EG', ] ],
        'YAMAHA'        => [
            'models' => [
                'AG-200',
                'DT-125',
                'DT-175',
                'DT-200',
                'DT-250',
                'ENDURO',
                'FB-100',
                'RT 100',
                'RX-ESPECIAL MOTOCICLETA',
                'S-85',
                'TDM 850',
                'TT-600',
                'T105E',
                'V-80',
                'VIRAGO',
                'XT-350',
                'XT660R',
                'XVS1100 A DRAGSTAR CLAS',
                'YB-125',
                'YB-80',
                'YB-90',
                'YD-110',
                'YT-115',
                '185',
            ]
        ],
        'YAMATI'        => [
            'models' => [
                'ALCON 4X2',
                'CARGO 200',
                'CARRIER 1050S',
                'CARRIER 1300S EFI',
                'GT-150',
                '4X2',
            ]
        ],
        'YAMWNA'        => [ 'models' => [ 'YAMWNA', ] ],
        'YINHE'         => [ 'models' => [ 'YH125-2', ] ],
        'YUEJIN'        => [
            'models' => [
                '4X2 (SIMPLE)',
                '4X2 NJ1063DA (SIMPLE)',
                'NJD-131',
            ]
        ],
        'ZNA'           => [
            'models' => [
                'RICH',
                'RICH PICK UP',
                'SUCCE',
                'SUV',
            ]
        ],
        'ZOTYE'         => [ 'models' => [ 'HUNTER', ] ],
        'ZXAUTO'        => [
            'models' => [
                'ADMIRAL',
                'ADMIRAL C/D',
                'ADMIRAL C/S',
                'GRAND TIGER',
                'GRANDTIGER',
                'LANDMARK',
            ]
        ],
    ],
];